<h1 style="font-size=20pt;color:orange">Minicurso Analisis de Datos usando Python

# Parte 3 - Bibliotecas Python para Representacion y Manipulacion de Datos

### 3.1. Numpy

In [1]:
import numpy as np

In [2]:
lista1 = [1, 2, 3]
array1 = np.array(lista1)
print(lista1)
print(array1)
print(array1.shape)
print(type(lista1))
print(type(array1))

[1, 2, 3]
[1 2 3]
(3,)
<class 'list'>
<class 'numpy.ndarray'>


In [5]:
lista2 = [
    [1, 2, 3], 
    [3, 4, 5]]
array2 = np.array(lista2)
print(array2)
print(array2.shape)
print('linea 1: {}'.format(array2[0]))
print('media: {}'.format(np.average(array2)))

[[1 2 3]
 [3 4 5]]
(2, 3)
linea 1: [1 2 3]
media: 3.0


In [4]:
array1 + array2

array([[2, 4, 6],
       [4, 6, 8]])

In [5]:
array1 * array2

array([[ 1,  4,  9],
       [ 3,  8, 15]])

In [6]:
a = np.zeros((3, 5))
print(a)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [7]:
type(a[0,0])

numpy.float64

In [8]:
b = np.zeros((5,), dtype=np.int)
print(b)

[0 0 0 0 0]


In [9]:
type(b[0])

numpy.int64

In [10]:
# numpy.full(shape, fill_value, dtype=None)
np.full(5, 2, dtype=np.float)

array([ 2.,  2.,  2.,  2.,  2.])

In [6]:
# numpy.empty(shape, dtype=float)
np.empty([2, 3])

array([[4.9e-324, 9.9e-324, 1.5e-323],
       [1.5e-323, 2.0e-323, 2.5e-323]])

In [7]:
c = np.random.rand(2, 3)
c

array([[0.51731601, 0.09878192, 0.70081767],
       [0.08239081, 0.71812854, 0.0871132 ]])

In [8]:
np.transpose(c)

array([[0.51731601, 0.08239081],
       [0.09878192, 0.71812854],
       [0.70081767, 0.0871132 ]])

In [9]:
d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [10]:
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
# Primer columna
d[:, 0]

array([1, 4, 7])

In [16]:
d[:, 1]

array([2, 5, 8])

In [17]:
d[:, 0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [18]:
d[:, 2]

array([3, 6, 9])

In [22]:
X = d[:,0:2]
y = d[:,2]
print(X)
print('')
print(y)

[[1 2]
 [4 5]
 [7 8]]

[3 6 9]


#### Notacion: start:stop:step

In [11]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x[1:7:2]

array([1, 3, 5])

#### Guardar e Leer un arquivo

In [13]:
import os
os.getcwd()

'/Users/epidemiology/Dropbox/Consultancy/Minicurso_Python/jupyter-notebooks-master'

In [15]:
np.save('x.npy', x)
del(x)
x = np.load('x.npy')
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [38]:
# Ver tamaño en memoria
from sys import getsizeof
x = np.zeros((1000,100),dtype='int')
print("Tamaño en memoria: " + str(getsizeof(x)))

x = np.zeros((1000,100),dtype='int32')
print("Tamaño en memoria: " + str(getsizeof(x)))

x = np.zeros((1000,100),dtype='float')
print("Tamaño en memoria: " + str(getsizeof(x)))

x = np.zeros((1000,100),dtype='float32')
print("Tamaño en memoria: " + str(getsizeof(x)))

Tamaño en memoria: 800120
Tamaño en memoria: 400120
Tamaño en memoria: 800120
Tamaño en memoria: 400120


In [28]:
# Utilice el mapeo de memoria cuando el contenido no quepa en la memoria RAM 
x_mm = np.memmap('x_mm.npy', dtype='float32', mode='w+', shape=(1000, 100))
"Tamaño en memoria: " + str(getsizeof(x_mm))

'Tamaño en memoria: 144'

In [29]:
x_mm[999][99] = 12.5
print(x_mm[999][99])

# Delete the memmap instance to close the file (the mmap file is not deleted). 
# Deletion flushes memory changes to disk before removing the object.
del(x_mm)

# Load
x_mm = np.memmap('x_mm.npy', dtype='float32', mode='r', shape=(1000, 100))
print(x_mm[999][99])

12.5
12.5
